# Welcome to Jekyll!
# https://github.com/pschfr/photos

title: Photos
tagline: Selected photos taken by Paul Schaefer
email: yeppaul2@gmail.com
description: A place for me to show off my photography. Work in progress, stay tuned.
baseurl:
url: https://paultakes.photos

exclude:
- node_modules
- gulpfile.js
- README.md
- LICENSE

sass:
    style: compressed

# The HTML is compressed via _layouts/compress.html
# http://jch.penibelst.de/
